# Generated by Django 3.0 on 2021-06-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='album',
            field=models.ImageField(default=0, upload_to='media/albums/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(upload_to='media/albums/'),
        ),
    ]
