# Generated by Django 3.0 on 2021-06-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_auto_20210622_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ImageField(upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(upload_to='albums/'),
        ),
    ]
