# Generated by Django 3.0 on 2021-06-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
