# Generated by Django 3.0 on 2021-06-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_tour'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tour',
            table='Tour',
        ),
    ]
