# Generated by Django 3.0 on 2021-06-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_auto_20210621_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('binNum', models.BinaryField()),
                ('HaveLaptop', models.BinaryField(default=False)),
                ('dob', models.DateField()),
                ('cur_time', models.DateTimeField(auto_now=True)),
                ('Petrol_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Duration', models.DurationField()),
                ('SSCCertificate', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'ModelFields',
            },
        ),
    ]
