# Generated by Django 3.0 on 2021-06-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_modelfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfields',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
    ]
