# Generated by Django 3.0 on 2021-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_auto_20210622_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfields',
            name='Address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelfields',
            name='Enter_Positive_Number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelfields',
            name='Enter_Small_Positive',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelfields',
            name='FavNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelfields',
            name='HaveAnyLoan',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='modelfields',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelfields',
            name='photo',
            field=models.ImageField(default=0, height_field=100, upload_to='', width_field=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelfields',
            name='sscGrade',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
