# Generated by Django 3.0 on 2021-06-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0008_auto_20210622_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfields',
            name='sscGrade',
        ),
    ]
